# Generated by Django 6.0.4 on 2026-04-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_alter_leaverequest_status_alter_leavetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Approved', 'approved'), ('Rejected', 'rejected'), ('pending', 'Pending')], default='pending', max_length=30),
        ),
    ]
